/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/bsVsrALVRHG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
// import second from '../../../public/'
import { Label } from "../../components/ui/label"
import { Input } from "../../components/ui/input"
import { Button } from "../../components/ui/button"
import { useEffect, useRef, useState } from "react";

export function SearchAd() {
  const [isFocused, setIsFocused] = useState(false);
  const handleFocus = () => {
    // console.log(isFocused)
    setIsFocused(!isFocused);

    
};
  const ref=useRef()
  useEffect(() => {
   
  }, [])
  
  return (
    (<section id="search" className="w-full bg-[url('../../../public/download.png')] bg-repeat-x bg-bottom py-12 md:py-16 lg:py-20 ">
      <div className="container mx-auto px-4 md:px-6 ">
        <div className="mx-auto max-w-2xl text-center shadow-2xl shadow-slate-400 rounded-lg bg-white     p-6">
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Find Your Property</h1>
          <p  className="mt-4 text-gray-500 dark:text-gray-400">Search for your <Button  onClick={handleFocus} ref={ref} className={!isFocused?`bg-[#23970C]  text-white`:`bg-transparent text-black`}>Dream Home</Button> or <Button  onClick={handleFocus} ref={ref} className={isFocused?`bg-[#23970C]  text-white`:`bg-transparent text-black`}>Investment Property</Button>.</p>
          <form className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-3">
            <div>
              <Label className="sr-only" htmlFor="city">
                City
              </Label>
              <Input 
           
                className="w-full rounded-md border-gray-300 shadow-sm "
                id="city"
                placeholder="City"
                type="text" />
            </div>
            <div>
              <Label className="sr-only" htmlFor="country">
                Country
              </Label>
              <Input
                className="w-full rounded-md border-gray-300 shadow-sm "
                id="country"
                placeholder="Country"
                type="text" />
            </div>
            <div>
              <Button className="w-full bg-transparent border hover:bg-gray-100 border-gray-300 text-green-500" type="submit">
                Find
              </Button>
            </div>
          </form>
        </div>
      </div>
    </section>)
  );
}
