/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CB4cZVFGzAV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "../../components/ui/carousel"

export function AdSlider() {
  return (
    (<Carousel className="w-full max-w-6xl h-[300px] " id='slider'>
      <CarouselContent className='h-[300px]'>
        <CarouselItem>
          <div
            className="relative h-[400px] sm:h-[200px] lg:h-[300px] overflow-hidden rounded-lg">
            <img
              alt="Property Ad 1"
              className="w-full h-full object-cover"
              height={300}
              src="https://images.olx.com.pk/thumbnails/446273392-800x600.webp"
              style={{
                aspectRatio: "1200/600",
                objectFit: "cover",
              }}
              width={1200} />
            <div
              className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent p-6 sm:p-8 lg:pl-14 lg:pb-4 flex flex-col justify-end">
              <h3 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-white mb-2">
                Luxury Penthouse in the Heart of the City
              </h3>
              <p className="text-base sm:text-lg lg:text-xl text-white">
                Experience the ultimate in urban living with this stunning penthouse, featuring breathtaking views and
                high-end finishes.
              </p>
            </div>
          </div>
        </CarouselItem>
        <CarouselItem>
          <div
            className="relative h-[400px] sm:h-[500px] lg:h-[600px] overflow-hidden rounded-lg">
            <img
              alt="Property Ad 2"
              className="w-full h-full object-cover"
              height={600}
              src="https://media.zameen.com/thumbnails/249226195-400x300.jpeg"
              style={{
                aspectRatio: "1200/600",
                objectFit: "initial",
              }}
              width={1200} />
            <div
              className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent p-6 sm:p-8 lg:p-10 flex flex-col justify-end">
              <h3 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-white mb-2">
                Spacious Family Home with Stunning Views
              </h3>
              <p className="text-base sm:text-lg lg:text-xl text-white">
                This beautiful family home offers ample living space, a large backyard, and breathtaking views of the
                surrounding countryside.
              </p>
            </div>
          </div>
        </CarouselItem>
        <CarouselItem>
          <div
            className="relative h-[400px] sm:h-[500px] lg:h-[600px] overflow-hidden rounded-lg">
            <img
              alt="Property Ad 3"
              className="w-full h-full object-cover"
              height={600}
              src="https://www.zameen.com/assets/imageBackground.eead38bf07e50d631ebf1c81f22574fe.jpg"
              style={{
                aspectRatio: "1200/600",
                objectFit: "cover",
              }}
              width={1200} />
            <div
              className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent p-6 sm:p-8 lg:p-10 flex flex-col justify-end">
              <h3 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-white mb-2">
                Modern Loft Apartment with Stunning City Views
              </h3>
              <p className="text-base sm:text-lg lg:text-xl text-white">
                This contemporary loft apartment offers open-plan living, high ceilings, and panoramic views of the city
                skyline.
              </p>
            </div>
          </div>
        </CarouselItem>
      </CarouselContent>
      <CarouselPrevious
        className="absolute top-1/2 -translate-y-1/2 left-4 z-10 text-white hover:text-gray-300 transition-colors">
        <ChevronLeftIcon className="h-8 w-8" />
      </CarouselPrevious>
      <CarouselNext
        className="absolute top-1/2 -translate-y-1/2 right-4 z-10 text-white hover:text-gray-300 transition-colors">
        <ChevronRightIcon className="h-8 w-8" />
      </CarouselNext>
    </Carousel>)
  );
}

function ChevronLeftIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m15 18-6-6 6-6" />
    </svg>)
  );
}


function ChevronRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9 18 6-6-6-6" />
    </svg>)
  );
}
